language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
script: cd tests ; for py in $(ls test_*.py); do python $py ; done
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq libblas-dev libatlas-dev liblapack-dev gfortran